### ISSUE TITLE
Bug: I can't see result because there are some errors in console and application crashes

### ISSUE THREAD

**Issue by hosseind88** [sepehrity/my-snapp-extension#15]
<img width="1680" alt="Screen Shot 2021-07-25 at 5 30 10 PM" src="https://user-images.githubusercontent.com/72156162/126899906-ca1e0649-468c-487a-b715-d6be6835dd43.png">

**Comment by sepehrity** [comment]
Oh, let me check. Thanks for reporting.

**Comment by sepehrity** [comment]
I forgot to wrap the lazy component with `React.Suspense` 🤦

**Comment by sepehrity** [comment]
@hosseind88 The issue should be fixed now.
Could you please confirm it's also working on your end?

**Comment by hosseind88** [comment]
yes I deleted extention and installed it again, and now it's fixed, thanks

**Comment by sepehrity** [comment]
@hosseind88 great, thanks. So we can close the issue 🎉
